export interface ReportModel {
  reportId: number,
  reportName: string,
  reportDesc: string,
  priority: string,
  fromTableName: string,
  joinConditionWithTable: string,
  fileType: string,
  region: string,
  headers: string,
  delimiter: string,
  fnameCondition: string,
  actionCondition: string,
  headers_2: string,
  headersCount: string,
  fileName: string,
  ctlFileName: string,
  reportGroupId: string,
}
